FROM ubuntu:latest

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip \
  && pip install ipython \

RUN touch /root/.bashrc \
  && echo 'export PYTHONDONTWRITEBYTECODE=1' > /root/.bashrc \
  && echo 'unset HISTFILE' >> /root/.bashrc
CMD mkdir /root/project
WORKDIR /root/project
